// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _7mart2024;

#nullable disable

namespace _7mart2024.Migrations
{
    [DbContext(typeof(ArabaDBContext))]
    [Migration("20240311163028_ArabaDataBase")]
    partial class ArabaDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.Property<int>("ArabalarID")
                        .HasColumnType("int");

                    b.Property<int>("MuhendislerMuhendisID")
                        .HasColumnType("int");

                    b.HasKey("ArabalarID", "MuhendislerMuhendisID");

                    b.HasIndex("MuhendislerMuhendisID");

                    b.ToTable("ArabaMuhendis");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Araba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("KisiID")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlakaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KisiID");

                    b.HasIndex("PlakaID")
                        .IsUnique();

                    b.ToTable("Arabalar");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Kisi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Muhendis", b =>
                {
                    b.Property<int>("MuhendisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuhendisID"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuhendisID");

                    b.ToTable("Muhendisler");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Plaka", b =>
                {
                    b.Property<int>("PlakaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlakaID"));

                    b.Property<string>("Numara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlakaID");

                    b.ToTable("Plakalar");
                });

            modelBuilder.Entity("ArabaMuhendis", b =>
                {
                    b.HasOne("_7mart2024.Entitites.Araba", null)
                        .WithMany()
                        .HasForeignKey("ArabalarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_7mart2024.Entitites.Muhendis", null)
                        .WithMany()
                        .HasForeignKey("MuhendislerMuhendisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_7mart2024.Entitites.Araba", b =>
                {
                    b.HasOne("_7mart2024.Entitites.Kisi", "Kisi")
                        .WithMany("Arabalar")
                        .HasForeignKey("KisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_7mart2024.Entitites.Plaka", "Plaka")
                        .WithOne("Araba")
                        .HasForeignKey("_7mart2024.Entitites.Araba", "PlakaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");

                    b.Navigation("Plaka");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Kisi", b =>
                {
                    b.Navigation("Arabalar");
                });

            modelBuilder.Entity("_7mart2024.Entitites.Plaka", b =>
                {
                    b.Navigation("Araba")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
